apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ugcloadtest
  region: eu-west-2

iam:
  withOIDC: true
 # serviceAccounts:
 # - metadata:
 #     name: ugcupload-jmeter
 #     # if no namespace is set, "default" will be used;
 #     # the namespace will be created if it doesn't exist already
 #     namespace: ugcloadtest-jmeter-ns
 #     labels: {aws-usage: "application"}
 #   attachPolicyARNs:
 #   - "arn:aws:iam::546933502184:policy/ugcupload-eks-jmeter-policy"

nodeGroups:
  - name: jmeter-slaves-v3
    labels: { jmeter_mode : slaves }
    minSize: 2
    maxSize: 50
    volumeSize: 50
    volumeType: gp2
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        ebs: true
    instanceType: t2.micro

  - name: jmeter-master-v3
    labels: { jmeter_mode : master }
    minSize: 1
    maxSize: 25
    volumeSize: 50
    volumeType: gp2
    instanceType: t2.small
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        ebs: true

  - name: grafana-v3
    labels: { report : grafana }
    minSize: 1
    volumeSize: 50
    volumeType: gp2
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        ebs: true
    instanceType: t2.micro
    kubeletExtraConfig:
         featureGates:
            CSINodeInfo: true
            CSIDriverRegistry: true
            CSIBlockVolume: true
            RotateKubeletServerCertificate: true # according to this must always be included: https://eksctl.io/usage/customizing-the-kubelet/

  - name: influxdb-v3
    labels: { report : influxd }
    minSize: 1
    volumeSize: 50
    volumeType: gp2
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        ebs: true
    instanceType: t2.micro

  - name: admin-controller-v3
    labels: { control : admin }
    minSize: 1
    volumeSize: 50
    volumeType: gp2
    ssh:
      allow: true
      publicKeyName: 'loadtest-controller'
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        ebs: true
    instanceType: t2.medium

cloudWatch:
  clusterLogging:
    # enable specific types of cluster control plane logs
    enableTypes: ["all"]
    # all supported types: "api", "audit", "authenticator", "controllerManager", "scheduler"
    # supported special values: "*" and "all"

