apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-jmeter
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
  storageClassName: ebs-sc
---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: influxdb-jmeter
  labels:
    app: influxdb-jmeter
spec:
  replicas: 1
  serviceName: influxdb-jmeter
  selector:
    matchLabels:
      app: influxdb-jmeter
  template:
    metadata:
      labels:
        app: influxdb-jmeter
    spec:
      serviceAccountName: ugcupload-jmeter
      containers:
        - image: influxdb
          imagePullPolicy: IfNotPresent
          name: influxdb
          volumeMounts:
          - name: config-volume
            mountPath: /etc/influxdb
          - name: influxdb-jmeter
            mountPath: /var/lib/influxdb
          ports:
            - containerPort: 8083
              name: influx
            - containerPort: 8086
              name: api
            - containerPort: 2003
              name: graphite
      volumes:
      - name: config-volume
        configMap:
      - name: influxdb-jmeter
        persistentVolumeClaim:
           claimName: influxdb-jmeter
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb-jmeter
  labels:
    app: influxdb-jmeter
spec:
  ports:
    - port: 8083
      name: http
      targetPort: 8083
    - port: 8086
      name: api
      targetPort: 8086
    - port: 2003
      name: graphite
      targetPort: 2003
  clusterIP: None
  selector:
    app: influxdb-jmeter