kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ugcuploader-admin-controller
subjects:
- kind: ServiceAccount
  name: ugcupload-control
  namespace: control
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
